### PR TITLE
[NDTensors] Fix issue in `Tensor` constructor when storage involves wrapper types

### LINKED ISSUE #1438: [NDTensors] [BUG] Constructing a Tensor from a view of another tensor can fail
**Description of bug**

There is an issue when one tries to construct a new tensor from the view of another tensor. It comes from the parameters of the new tensor being defined before the storage is copied, i.e. a type mismatch.

<details><summary>Minimal runnable code</summary><p>

```julia
using ITensors: Index
using NDTensors: randomTensor, Tensor
i,j = Index.((4,4))
t = randomTensor((i,j))
Tensor(storage(t[1:2, 1:2]), (2, 2))
```
</p></details>

<details><summary>Output of minimal runnable code</summary><p>

```julia
ERROR: MethodError: Cannot `convert` an object of type Vector{Float64} to an object of type Base.ReshapedArray{Float64, 1, SubArray{Float64, 2, Matrix{Float64}, Tuple{UnitRange{Int64}, UnitRange{Int64}}, false}, Tuple{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64}}}

Closest candidates are:
  convert(::Type{T}, ::T) where T
   @ Base Base.jl:84
  convert(::Type{T}, ::LinearAlgebra.Factorization) where T<:AbstractArray
   @ LinearAlgebra ~/.julia/juliaup/julia-1.10.2+0.aarch64.apple.darwin14/share/julia/stdlib/v1.10/LinearAlgebra/src/factorization.jl:108
  convert(::Type{T}, ::T) where T<:AbstractArray
   @ Base abstractarray.jl:16
  ...

Stacktrace:
 [1] convert(::Type{NDTensors.Dense{Float64, Base.ReshapedArray{…}}}, D::NDTensors.Dense{Float64, Vector{Float64}})
   @ NDTensors ~/.julia/dev/ITensors/NDTensors/src/dense/dense.jl:142
 [2] NDTensors.DenseTensor{…}(::NDTensors.AllowAlias, storage::NDTensors.Dense{…}, inds::Tuple{…})
   @ NDTensors ~/.julia/dev/ITensors/NDTensors/src/tensor/tensor.jl:27
 [3] NDTensors.DenseTensor{…}(::NDTensors.NeverAlias, storage::NDTensors.Dense{…}, inds::Tuple{…})
   @ NDTensors ~/.julia/dev/ITensors/NDTensors/src/tensor/tensor.jl:36
 [4] Tensor(as::NDTensors.NeverAlias, storage::NDTensors.Dense{Float64, Base.ReshapedArray{…}}, inds::Tuple{Int64, Int64})
   @ NDTensors ~/.julia/dev/ITensors/NDTensors/src/tensor/tensor.jl:67
 [5] Tensor(storage::NDTensors.Dense{Float64, Base.ReshapedArray{…}}, inds::Tuple{Int64, Int64})
   @ NDTensors ~/.julia/dev/ITensors/NDTensors/src/tensor/tensor.jl:81
 [6] top-level scope
   @ Untitled-1:16
Some type information was truncated. Use `show(err)` to see complete types.
```
</p></details>

**Version information**

 - Output from `versioninfo()`:
```julia
julia> versioninfo()
Julia Version 1.10.2
Commit bd47eca2c8a (2024-03-01 10:14 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: macOS (arm64-apple-darwin22.4.0)
  CPU: 10 × Apple M1 Max
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-15.0.7 (ORCJIT, apple-m1)
Threads: 1 default, 0 interactive, 1 GC (on 8 virtual cores)
Environment:
  LD_LIBRARY_PATH = /Users/kpierce/Software/triqs/triqs_install/lib::/opt/intel/oneapi/mkl/latest/lib
  JULIA_EDITOR = code
  JULIA_NUM_THREADS = 
```

**Proposed solution**

The code stack calls 
```julia
function Tensor(as::AliasStyle, storage::TensorStorage, inds::Tuple)
  return Tensor{eltype(storage),length(inds),typeof(storage),typeof(inds)}(
    as, storage, inds
  )
end
```
which calls 
```julia
function Tensor{ElT,N,StoreT,IndsT}(
  ::NeverAlias, storage::TensorStorage, inds
) where {ElT,N,StoreT<:TensorStorage,IndsT}
  return Tensor{ElT,N,StoreT,IndsT}(AllowAlias(), copy(storage), inds)
end
```
In the first call 
```julia
typeof(storage(t[1:2, 1:2])) = NDTensors.Dense{Float64, Base.ReshapedArray{Float64, 1, SubArray{Float64, 2, Matrix{Float64}, Tuple{UnitRange{Int64}, UnitRange{Int64}}, false}, Tuple{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64}}}}
```
and when the type of the copied storage is 
```julia
typeof(copy(storage(t[1:2, 1:2])))
NDTensors.Dense{Float64, Vector{Float64}}
```
So my proposal is to modify the second tensor constructor to be
```julia
function Tensor{ElT,N,StoreT,IndsT}(
  ::NeverAlias, storage::TensorStorage, inds
) where {ElT,N,StoreT<:TensorStorage,IndsT}
  store = copy(storage)
  return Tensor{ElT,N,typeof(store),IndsT}(AllowAlias(), store, inds)
end
```
which returns the following output
```julia
julia> Tensor(storage(t[1:2, 1:2]), (2,2)) 
Dim 1: 2
Dim 2: 2
NDTensors.Dense{Float64, Vector{Float64}}
 2×2
 -0.8736954509592826   0.30952483312000373
  1.6882572502541735  -0.7830143316102207
```

### PR DESCRIPTION
**Pull request by kmp5VT**
This is the proposed solution from issue 1438 and should make it possible now to create a copy `Tensor/ITensor` from a view of another `Tensor/ITensor`.  I also fixed an additional constructor in UnallocatedArrays that should say `UnallocatedX` instead of `new` I am adding a test for that in the unittests now

Fixes #1438.

### CODE REVIEW

File: NDTensors/src/lib/UnallocatedArrays/test/runtests.jl [hunk 1]
```diff
@@ -73,7 +73,7 @@ using .NDTensorsTestUtils: devices_list
     Fc[2, 3, 4] = elt(0)
     @test iszero(Fc[2, 3, 4])
 
-    F = UnallocatedFill(f, dev(Array))
+    F = UnallocatedFill{elt}(f, dev(Array))
```
Comment (kmp5VT) [inline NDTensors/src/lib/UnallocatedArrays/test/runtests.jl:76]: When passing the `FillArray` and `Alloctype` into `UnallocatedX` the code does not use the code stack that incrementally specifies `{ElT, N, AxesT, AllocT}` but by adding `elt` I force it to use that stack and verify that the code works as expected

File: NDTensors/src/tensor/tensor.jl [hunk 2]
```diff
@@ -33,7 +33,8 @@ end
 function Tensor{ElT,N,StoreT,IndsT}(
   ::NeverAlias, storage::TensorStorage, inds
 ) where {ElT,N,StoreT<:TensorStorage,IndsT}
-  return Tensor{ElT,N,StoreT,IndsT}(AllowAlias(), copy(storage), inds)
+  store = copy(storage)
+  return Tensor{ElT,N,typeof(store),IndsT}(AllowAlias(), store, inds)
 end
```
Comment (mtfishman) [inline NDTensors/src/tensor/tensor.jl:38]: I don't think this proposed change is a good idea. Calling `Tensor{ElT,N,StoreT,IndsT}(NeverAlias(), storage, inds)` should only ever construct an object of type `Tensor{ElT,N,StoreT,IndsT}`. More generally, constructors of a type `T` should obey `T(args...) isa T`, as we have discussed in the past. We should consider that to be a "law" of designing Julia code, even if it isn't enforced by the compiler.

**Comment by mtfishman** [comment]
Can you split off the fixes to `UnallocatedArrays` into a separate PR?

File: NDTensors/src/tensor/tensor.jl (hunk 2 above)
Comment (kmp5VT) [reply NDTensors/src/tensor/tensor.jl:38]: Ah right, the type conversion did seem sketchy to me. I'll rework this. Thanks!

File: NDTensors/test/test_dense.jl [hunk 3]
```diff
@@ -38,6 +38,11 @@ NDTensors.dim(i::MyInd) = i.dim
 
       Aview = A[2:3, 2:3]
       @test dims(Aview) == (2, 2)
+      ## Added for issue 1431 create a tensor from 
+      ## a sliced view of another tensor
+      Acopy = Tensor(NDTensors.storage(Aview), (1,4))
```
Comment (kmp5VT) [inline NDTensors/test/test_dense.jl:43]: @mtfishman I am not sure if I should add a test here since this constructor uses an internal `NDTensors` function.

Comment (mtfishman) [reply NDTensors/test/test_dense.jl:43]: Is the internal function you are referring to `NDTensors.storage(...)`? I think it is ok to use that in the tests.

Comment (kmp5VT) [reply NDTensors/test/test_dense.jl]: Yes it is. Thanks!

**Comment by mtfishman** [comment]
Looks good, thanks. I'm going to double check that this fixes the issue I originally saw in https://github.com/JanReimers/ITensorMPOCompression.jl/pull/7 once I change that over to constructing the ITensor from the storage, but otherwise this looks good to go.

I see a failure in the Metal tests but maybe that is just a random failure unrelated to this PR?

**Comment by mtfishman** [comment]
Ok, I checked that this fixes the issue I was seeing in https://github.com/JanReimers/ITensorMPOCompression.jl/pull/7 so I'll merge once tests pass.
