### PR TITLE
[ITensors] Fix `checkflux` for QN ITensor with no blocks

### LINKED ISSUE #1209: [ITensors] [BUG] QN correlation matrix not working since #1178
**Description of bug**

Repeat of #1179

When computing the correlation matrix of two operators which when acted together on the same site give zero with a quantum number conserving MPS I get an error.

**Minimal code demonstrating the bug or unexpected behavior**

<details><summary>Minimal runnable code</summary><p>

```julia
using ITensors
opP = Int32[1 0 0 0; 0 0 0 0; 0 0 0 0; 0 0 0 0]
opQ = Int32[0 0 0 0; 0 1 0 0; 0 0 0 0; 0 0 0 0]
sites = siteinds("Electron", 4; conserve_qns=true)
psi = MPS(sites, ["Up" for n in 1:4])
correlation_matrix(psi, opP, opQ)
```
</p></details>

**Expected output or behavior**

The correlation matrix is computed.

**Actual output or behavior**

Bounds error

<details><summary>Output of minimal runnable code</summary><p>

```
ERROR: BoundsError: attempt to access 0-element Vector{Block{2}} at index [1]
Stacktrace:
  [1] getindex
    @ ./essentials.jl:13 [inlined]
  [2] first
    @ ./abstractarray.jl:445 [inlined]
  [3] checkflux(T::NDTensors.BlockSparseTensor{Int32, 2, Tuple{Index{Vector{Pair{QN, Int64}}}, Index{Vector{Pair{QN, Int64}}}}, NDTensors.BlockSparse{Int32, Vector{Int32}, 2}})
    @ ITensors ~/.julia/packages/ITensors/yZbTa/src/qn/flux.jl:50
  [4] ITensor(::NDTensors.AllowAlias, elt::Type{Int32}, A::Matrix{Int32}, inds::Vector{Index{Vector{Pair{QN, Int64}}}}; tol::Float64, checkflux::Bool)
    @ ITensors ~/.julia/packages/ITensors/yZbTa/src/qn/qnitensor.jl:316
  [5] ITensor(::NDTensors.AllowAlias, elt::Type{Int32}, A::Matrix{Int32}, inds::Vector{Index{Vector{Pair{QN, Int64}}}})
    @ ITensors ~/.julia/packages/ITensors/yZbTa/src/qn/qnitensor.jl:297
  [6] ITensor(::NDTensors.AllowAlias, ::Matrix{Int32}, ::Vector{Index{Vector{Pair{QN, Int64}}}}, ::Vararg{Vector{Index{Vector{Pair{QN, Int64}}}}}; kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ ITensors ~/.julia/packages/ITensors/yZbTa/src/itensor.jl:402
  [7] ITensor(::NDTensors.AllowAlias, ::Matrix{Int32}, ::Vector{Index{Vector{Pair{QN, Int64}}}}, ::Vararg{Vector{Index{Vector{Pair{QN, Int64}}}}})
    @ ITensors ~/.julia/packages/ITensors/yZbTa/src/itensor.jl:399
  [8] itensor(::Matrix{Int32}, ::Vararg{Any}; kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ ITensors ~/.julia/packages/ITensors/yZbTa/src/itensor.jl:134
  [9] itensor
    @ ~/.julia/packages/ITensors/yZbTa/src/itensor.jl:134 [inlined]
 [10] op(X::Matrix{Int32}, s::Index{Vector{Pair{QN, Int64}}})
    @ ITensors ~/.julia/packages/ITensors/yZbTa/src/physics/sitetype.jl:435
 [11] #op#1092
    @ ~/.julia/packages/ITensors/yZbTa/src/physics/sitetype.jl:464 [inlined]
 [12] op
    @ ~/.julia/packages/ITensors/yZbTa/src/physics/sitetype.jl:463 [inlined]
 [13] #op#1095
    @ ~/.julia/packages/ITensors/yZbTa/src/physics/sitetype.jl:468 [inlined]
 [14] op(opname::Matrix{Int32}, s::Vector{Index{Vector{Pair{QN, Int64}}}}, ns::Int64)
    @ ITensors ~/.julia/packages/ITensors/yZbTa/src/physics/sitetype.jl:467
 [15] correlation_matrix(psi::MPS, _Op1::Matrix{Int32}, _Op2::Matrix{Int32}; sites::UnitRange{Int64}, site_range::Nothing, ishermitian::Nothing)
    @ ITensors ~/.julia/packages/ITensors/yZbTa/src/mps/mps.jl:796
 [16] correlation_matrix(psi::MPS, _Op1::Matrix{Int32}, _Op2::Matrix{Int32})
    @ ITensors ~/.julia/packages/ITensors/yZbTa/src/mps/mps.jl:714
 [17] top-level scope
    @ REPL[12]:1
```

</p></details>

**Version information**

 - Output from `versioninfo()`:
```julia
julia> versioninfo()
Julia Version 1.9.2
Commit e4ee485e909 (2023-07-05 09:39 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 24 × 13th Gen Intel(R) Core(TM) i7-13700KF
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, goldmont)
  Threads: 1 on 24 virtual cores
Environment:
  JULIA_REVISE_POLL = 1
```
 - Output from `using Pkg; Pkg.status("ITensors")`:
```julia
julia> using Pkg; Pkg.status("ITensors")
Status `~/.julia/environments/v1.9/Project.toml`
  [9136182c] ITensors v0.3.43
```

Note that this worked as expected in v0.3.41 before #1178 added `checkflux` in the QN tensor construction.

### PR DESCRIPTION
**Pull request by emstoudenmire**
Fixes #1209  by allowing `checkflux` to work when block-sparse ITensors are created which have no blocks. 

The bug was coming from `correlation_matrix` due to user-specific operators whose onsite product turned out to be numerically zero (zero matrix), leading to no blocks. This is ok, but the `checkflux` function was assuming at least one non-zero block and failing in the case of zero blocks.

### CODE REVIEW

File: src/qn/flux.jl [hunk 1]
```diff
@@ -34,20 +34,20 @@ function flux(T::Tensor)
...
 end
 
 function checkflux(T::Tensor)
-  b1 = first(nzblocks(T))
-  fluxTb1 = flux(T, b1)
+  nzb = nzblocks(T)
+  isempty(nzb) && return nothing
+  fluxTb1 = flux(T, first(nzb))
   return checkflux(T, fluxTb1)
 end
```
Comment (mtfishman) [inline src/qn/flux.jl:53]: Another way to write these functions would be:
```julia
allfluxequal(T::Tensor, flux_to_check) = all(b -> flux(T, b) == flux_to_check, nzblocks(T))
allfluxequal(T::Tensor) = mapreduce(b -> flux(T, b), ==, nzblocks(T); init=true)
checkflux(T::Tensor) = allfluxequal(T) || error("Fluxes not all equal")
checkflux(T::Tensor, flux) = allfluxequal(T, flux) || error("Fluxes not all equal")
```

Comment (emstoudenmire) [reply src/qn/flux.jl:53]: Those look nicer. I'll switch out the previous code for them.

**Comment by mtfishman** [comment]
Looks good from my end, ready to merge?

File: src/qn/flux.jl [hunk 2]
```diff
@@ -7,47 +6,75 @@ Returns the flux of the ITensor.
...
 
-function checkflux(T::ITensor, flux_check)
-  return checkflux(tensor(T), flux_check)
-end
+"""
+    checkflux(T::ITensor)
 
-function checkflux(T::ITensor)
-  return checkflux(tensor(T))
-end
```
Comment (emstoudenmire) [inline src/qn/flux.jl:20]: Here I was just turning some multi-line functions into single-line expressions, but they are the same code.

File: src/qn/flux.jl [hunk 3]
```diff
@@ -7,47 +6,75 @@ Returns the flux of the ITensor.
...
+flux(T::Tensor, block::Block) = flux(inds(T), block)
+
+"""
+    flux(T::Tensor, i::Integer, is::Integer...)
+
+Compute the flux of a specific element of a Tensor, 
+regardless of whether this element is zero or non-zero.
+"""
+flux(T::Tensor, i::Integer, is::Integer...) = flux(inds(T), i, is...)
+
```
Comment (emstoudenmire) [inline src/qn/flux.jl:48]: For the above two functions, I replaced `flux(T::Tensor, args...) = ` with explicit specializations for the case of Block and Integer arguments. All tests pass so these must be the only two cases we are using.

File: test/base/test_qnitensor.jl
Comment (emstoudenmire) [inline test/base/test_qnitensor.jl:1]: Just added some comments to this test, to help avoid the same confusions I just had in the future.

**Comment by emstoudenmire** [comment]
Just missed your comment. Thanks for reviewing. I'll merge.
