### PR TITLE
Fix behavior of factorize mindim

### LINKED ISSUE #1207: [ITensors] [BUG] Inconsistent Behavior of mindim
**Description of bug**

When using `mindim!`, the link dimension behavior at the "edge" is different depending on the value of `cutoff!`. 
If there is a cutoff, some tensors get set to the `mindim` while others are not, and if there isn't a cutoff (`cutoff!(sweeps,0)`) the link dimensions are symmetric.  I'm not sure which output is preferred but I suspect its the latter? 

**Minimal code demonstrating the bug or unexpected behavior**

<details><summary>Minimal runnable code</summary><p>

```julia
using ITensors

N = 32
sites = siteinds("S=1/2", N; conserve_qns=false)

ampo = AutoMPO()
for j in 1:(N - 1)
  ampo .+= 0.5, "S+", j, "S-", j + 1
  ampo .+= 0.5, "S-", j, "S+", j + 1
  ampo .+= "Sz", j, "Sz", j + 1
end
H = MPO(ampo, sites)

ψ₀ = randomMPS(sites)

sweeps = Sweeps(6)
maxdim!(sweeps, 4, 16, 64)
mindim!(sweeps, 1, 16,64,)
cutoff!(sweeps,1e-10)
noise!(sweeps, 0)
energy, ψ = @time dmrg(H, ψ₀, sweeps)
@show linkdims(ψ)
```
</p></details>

**Expected output or behavior**

<details><summary>Expected Output</summary><p>

If `cutoff!(sweeps,0)`:

```julia
linkdims(ψ) = [2, 4, 8, 16, 32, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 32, 16, 8, 4, 2]

```
</p></details>

**Actual output or behavior**

<details><summary>Output of minimal runnable code</summary><p>

```julia
linkdims(ψ) = [64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 32, 16, 8, 4, 2]

```
</p></details>

**Version information**

 - Output from `versioninfo()`:
```julia
julia> versioninfo()
Julia Version 1.8.5
Commit 17cfb8e65ea (2023-01-08 06:45 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 24 × Intel(R) Xeon(R) Gold 6128 CPU @ 3.40GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, skylake-avx512)
  Threads: 1 on 24 virtual cores

```
 - Output from `using Pkg; Pkg.status("ITensors")`:
```julia
julia> using Pkg; Pkg.status("ITensors")
Status `~/.julia/environments/v1.8/Project.toml`
  [9136182c] ITensors v0.3.43

```

### PR DESCRIPTION
**Pull request by ryanlevy**
# Description

Fixes #1207 

<details><summary>Minimal demonstration of previous behavior</summary><p>

> Quick update, a more minimal example. Say we have a two-site tensor that we want to factorize
> 
> ```julia
> s  = Index(2)
> s′ = Index(2)
> l = Index(64)
> r = Index(16)
> T = randomITensor(l,s,s′,r)
> ```
> 
> The inconsistent behavior manifests as
> 
> ```julia
> > L,R,spec = factorize(T,l,s; cutoff=0,mindim=64)
> > @show inds(L)
> inds(L) = ((dim=64|id=719), (dim=2|id=499), (dim=32|id=847|"Link,fact"))
> ```
> 
> where we get the 64->32->16 stepdown. Or with cutoff
> 
> ```julia
> > L,R,spec = factorize(T,l,s; cutoff=1e-10,mindim=64)
> > @show inds(L)
> inds(L) = ((dim=64|id=444), (dim=2|id=941), (dim=64|id=961|"Link,fact"))
> ```
> 
> Where the factorize respects the mindim by padding the link dimension. I think the `cutoff=0` behavior is best here.

</p></details>

<details><summary>Minimal demonstration of new behavior</summary><p>

```julia
using ITensors

s  = Index(2)
s′ = Index(2)
l = Index(64)
r = Index(16)
T = randomITensor(l,s,s′,r)

L,R,spec = factorize(T,l,s; cutoff=1e-10,maxdim=64,mindim=64)
@show inds(L)
@show inds(R)
```

```julia
> inds(L) = ((dim=64|id=96), (dim=2|id=968), (dim=32|id=502|"Link,fact"))
> inds(R) = ((dim=32|id=502|"Link,fact"), (dim=2|id=814), (dim=16|id=189))

```
</p></details>

# How Has This Been Tested?

No new tests

# Checklist:

- [x] My code follows the style guidelines of this project. Please run `using JuliaFormatter; format(".")` in the base directory of the repository (`~/.julia/dev/ITensors`) to format your code according to our style guidelines.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have added tests that verify the behavior of the changes I made.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

File: src/tensor_operations/matrix_decomposition.jl [hunk 1]
```diff
@@ -662,8 +662,9 @@ function factorize(A::ITensor, Linds...; kwargs...)
   # so eigen should only be used if a larger cutoff is requested)
   automatic_cutoff = 1e-12
   Lis = indices(Linds...)
-  dL, dR = dim(Lis), dim(indices(setdiff(inds(A), Lis)))
-  maxdim = get(kwargs, :maxdim, min(dL, dR))
+  dL, dR = dim(commoninds(inds(A), Lis)), dim(indices(setdiff(inds(A), Lis)))
```
Comment (mtfishman) [inline src/tensor_operations/matrix_decomposition.jl:665]:
```suggestion
  Lis = commoninds(A, indices(Linds...))
  Ris = uniqueinds(A, Lis)
  dL, dR = dim(Lis), dim(Ris)
```

File: src/tensor_operations/matrix_decomposition.jl [hunk 2]
```diff
@@ -662,8 +662,9 @@ function factorize(A::ITensor, Linds...; kwargs...)
...
+  # maxdim is forced to be at most the max given SVD
+  maxdim = min(get(kwargs, :maxdim, min(dL, dR)), min(dL, dR))
```
Comment (mtfishman) [inline src/tensor_operations/matrix_decomposition.jl:667]: Would you mind moving `maxdim` to the `factorize` function signature, say with `maxdim=nothing` to set a default of `nothing`? We are moving towards that style instead of using `get`. You'll have to then pass `maxdim` explicitly to `factorize_svd` and `factorize_eigen`.

File: src/tensor_operations/matrix_decomposition.jl [hunk 3]
```diff
@@ -662,8 +662,14 @@ function factorize(A::ITensor, Linds...; kwargs...)
   # so eigen should only be used if a larger cutoff is requested)
   automatic_cutoff = 1e-12
   Lis = indices(Linds...)
```
Comment (mtfishman) [inline src/tensor_operations/matrix_decomposition.jl:664]:
```suggestion
```

**Comment by mtfishman** [comment]
Thanks Ryan, could you add a test?

**Comment by mtfishman** [comment]
Thanks!
