### PR TITLE
[NDTensors] `Unwrap` module for dispatching on unwrapped types

### LINKED ISSUE #1193: [NDTensors] [BUG] Many basic tensor operations fail with CUDA extension due to `LoadError: Scalar indexing is disallowed.`
**Description of bug**

I am attempting to use the CUDA extension for NDTensors. I am finding that tensor contraction sometimes fails, along with other functions like `permute`, as well as the `NDTensors.generic_randn` call used in the example of the NDTensors CUDA extension (`NDTensors/ext/examples/NDTensorCUDA.jl`).

They all fail with `ERROR: LoadError: Scalar indexing is disallowed.` (or emit a similar warning in the REPL where scalar indexing is allowed).

**Minimal code demonstrating the bug or unexpected behavior**

<details><summary>Minimal runnable code</summary><p>

```julia
import CUDA
import ITensors
import NDTensors

i, j, k = ITensors.Index(3), ITensors.Index(5), ITensors.Index(2)
A, B = ITensors.randomITensor(i, j), ITensors.randomITensor(j, k)

# works when running script directly, but warns of scalar indexing in REPL
cuA, cuB = NDTensors.cu(A), NDTensors.cu(B)

contracted = cuA * cuB

@show NDTensors.cpu(contracted) ≈ A * B

# without @CUDA.allowscalar, fails with `ERROR: LoadError: Scalar indexing is disallowed.`
permuted = ITensors.permute(cuA, (j, i))
```
</p></details>

**Expected output or behavior**

`NDTensors.cu()` should work without warning in REPL on `ITensors.ITensor`, and `ITensors.permute` should work without the scalar indexing error.

**Actual output or behavior**

<details><summary>Output of minimal runnable code</summary><p>

```julia
NDTensors.cpu(contracted) ≈ A * B = true
ERROR: LoadError: Scalar indexing is disallowed.
Invocation of getindex resulted in scalar indexing of a GPU array.
This is typically caused by calling an iterating implementation of a method.
Such implementations *do not* execute on the GPU, but very slowly on the CPU,
and therefore are only permitted from the REPL for prototyping purposes.
If you did intend to index this array, annotate the caller with @allowscalar.
Stacktrace:
  [1] error(s::String)
    @ Base ./error.jl:35
  [2] assertscalar(op::String)
    @ GPUArraysCore ~/.julia/packages/GPUArraysCore/uOYfN/src/GPUArraysCore.jl:103
  [3] getindex
    @ ~/.julia/packages/GPUArrays/5XhED/src/host/indexing.jl:9 [inlined]
  [4] getindex
    @ ~/.julia/packages/StridedViews/MjjHH/src/stridedview.jl:97 [inlined]
  [5] macro expansion
    @ ~/.julia/packages/Strided/O8zfl/src/mapreduce.jl:330 [inlined]
  [6] macro expansion
    @ ./simdloop.jl:77 [inlined]
  [7] macro expansion
    @ ~/.julia/packages/Strided/O8zfl/src/mapreduce.jl:329 [inlined]
  [8] _mapreduce_kernel!(f::Strided.CaptureArgs{NDTensors.var"#69#70", Tuple{Strided.Arg, Strided.Arg}}, op::Nothing, initop::Nothing, dims::Tuple{Int64, Int64}, blocks::Tuple{Int64, Int64}, arrays::Tuple{StridedViews.StridedView{Float64, 2, CUDA.CuArray{Float64, 2, CUDA.Mem.DeviceBuffer}, typeof(identity)}, StridedViews.StridedView{Float64, 2, CUDA.CuArray{Float64, 2, CUDA.Mem.DeviceBuffer}, typeof(identity)}, StridedViews.StridedView{Float64, 2, CUDA.CuArray{Float64, 2, CUDA.Mem.DeviceBuffer}, typeof(identity)}}, strides::Tuple{Tuple{Int64, Int64}, Tuple{Int64, Int64}, Tuple{Int64, Int64}}, offsets::Tuple{Int64, Int64, Int64})
    @ Strided ~/.julia/packages/Strided/O8zfl/src/mapreduce.jl:229
  [9] _mapreduce_block!(f::Any, op::Any, initop::Any, dims::Tuple{Int64, Int64}, strides::Tuple{Tuple{Int64, Int64}, Tuple{Int64, Int64}, Tuple{Int64, Int64}}, offsets::Tuple{Int64, Int64, Int64}, costs::Tuple{Int64, Int64}, arrays::Tuple{StridedViews.StridedView{Float64, 2, CUDA.CuArray{Float64, 2, CUDA.Mem.DeviceBuffer}, typeof(identity)}, StridedViews.StridedView{Float64, 2, CUDA.CuArray{Float64, 2, CUDA.Mem.DeviceBuffer}, typeof(identity)}, StridedViews.StridedView{Float64, 2, CUDA.CuArray{Float64, 2, CUDA.Mem.DeviceBuffer}, typeof(identity)}})
    @ Strided ~/.julia/packages/Strided/O8zfl/src/mapreduce.jl:152
 [10] _mapreduce_order!(f::Any, op::Any, initop::Any, dims::Tuple{Int64, Int64}, strides::Tuple{Tuple{Int64, Int64}, Tuple{Int64, Int64}, Tuple{Int64, Int64}}, arrays::Tuple{StridedViews.StridedView{Float64, 2, CUDA.CuArray{Float64, 2, CUDA.Mem.DeviceBuffer}, typeof(identity)}, StridedViews.StridedView{Float64, 2, CUDA.CuArray{Float64, 2, CUDA.Mem.DeviceBuffer}, typeof(identity)}, StridedViews.StridedView{Float64, 2, CUDA.CuArray{Float64, 2, CUDA.Mem.DeviceBuffer}, typeof(identity)}})
    @ Strided ~/.julia/packages/Strided/O8zfl/src/mapreduce.jl:138
 [11] _mapreduce_fuse!
    @ ~/.julia/packages/Strided/O8zfl/src/mapreduce.jl:116 [inlined]
 [12] copyto!
    @ ~/.julia/packages/Strided/O8zfl/src/broadcast.jl:35 [inlined]
 [13] materialize!
    @ ./broadcast.jl:884 [inlined]
 [14] materialize!
    @ ./broadcast.jl:881 [inlined]
 [15] permutedims!(R::NDTensors.DenseTensor{Float64, 2, Tuple{ITensors.Index{Int64}, ITensors.Index{Int64}}, NDTensors.Dense{Float64, CUDA.CuArray{Float64, 1, CUDA.Mem.DeviceBuffer}}}, T::NDTensors.DenseTensor{Float64, 2, Tuple{ITensors.Index{Int64}, ITensors.Index{Int64}}, NDTensors.Dense{Float64, CUDA.CuArray{Float64, 1, CUDA.Mem.DeviceBuffer}}}, perm::Tuple{Int64, Int64}, f::NDTensors.var"#69#70")
    @ NDTensors ~/.julia/packages/NDTensors/olKso/src/dense/densetensor.jl:246
 [16] permutedims!!(R::NDTensors.DenseTensor{Float64, 2, Tuple{ITensors.Index{Int64}, ITensors.Index{Int64}}, NDTensors.Dense{Float64, CUDA.CuArray{Float64, 1, CUDA.Mem.DeviceBuffer}}}, T::NDTensors.DenseTensor{Float64, 2, Tuple{ITensors.Index{Int64}, ITensors.Index{Int64}}, NDTensors.Dense{Float64, CUDA.CuArray{Float64, 1, CUDA.Mem.DeviceBuffer}}}, perm::Tuple{Int64, Int64}, f::Function)
    @ NDTensors ~/.julia/packages/NDTensors/olKso/src/dense/densetensor.jl:188
 [17] permutedims!!
    @ ~/.julia/packages/NDTensors/olKso/src/dense/densetensor.jl:186 [inlined]
 [18] permutedims
    @ ~/.julia/packages/NDTensors/olKso/src/tensoralgebra/generic_tensor_operations.jl:5 [inlined]
 [19] permutedims
    @ ~/.julia/packages/ITensors/Qe99p/src/tensor_operations/permutations.jl:64 [inlined]
 [20] _permute(as::NDTensors.NeverAlias, T::NDTensors.DenseTensor{Float64, 2, Tuple{ITensors.Index{Int64}, ITensors.Index{Int64}}, NDTensors.Dense{Float64, CUDA.CuArray{Float64, 1, CUDA.Mem.DeviceBuffer}}}, new_inds::Tuple{ITensors.Index{Int64}, ITensors.Index{Int64}})
    @ ITensors ~/.julia/packages/ITensors/Qe99p/src/tensor_operations/permutations.jl:69
 [21] permute(as::NDTensors.NeverAlias, T::ITensors.ITensor, new_inds::Tuple{ITensors.Index{Int64}, ITensors.Index{Int64}})
    @ ITensors ~/.julia/packages/ITensors/Qe99p/src/tensor_operations/permutations.jl:73
 [22] #permute#271
    @ ~/.julia/packages/ITensors/Qe99p/src/tensor_operations/permutations.jl:54 [inlined]
 [23] permute(T::ITensors.ITensor, new_inds::Tuple{ITensors.Index{Int64}, ITensors.Index{Int64}})
    @ ITensors ~/.julia/packages/ITensors/Qe99p/src/tensor_operations/permutations.jl:38
 [24] top-level scope
    @ ~/it_test2/test.jl:17
in expression starting at /home/william/it_test2/test.jl:17
```
</p></details>

<details><summary>Output of `cuA, cuB = NDTensors.cu(A), NDTensors.cu(B)` in REPL</summary><p>

```julia
┌ Warning: Performing scalar indexing on task Task (runnable) @0x00007f5e6b5fc970.
│ Invocation of getindex resulted in scalar indexing of a GPU array.
│ This is typically caused by calling an iterating implementation of a method.
│ Such implementations *do not* execute on the GPU, but very slowly on the CPU,
│ and therefore are only permitted from the REPL for prototyping purposes.
│ If you did intend to index this array, annotate the caller with @allowscalar.
└ @ GPUArraysCore ~/.julia/packages/GPUArraysCore/uOYfN/src/GPUArraysCore.jl:
```
</p></details>

<details><summary>Also, running `NDTensors/ext/examples/NDTensorCUDA.jl` results in a similar error</summary><p>

```julia

ERROR: LoadError: Scalar indexing is disallowed.
Invocation of setindex! resulted in scalar indexing of a GPU array.
This is typically caused by calling an iterating implementation of a method.
Such implementations *do not* execute on the GPU, but very slowly on the CPU,
and therefore are only permitted from the REPL for prototyping purposes.
If you did intend to index this array, annotate the caller with @allowscalar.
Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:35
 [2] assertscalar(op::String)
   @ GPUArraysCore ~/.julia/packages/GPUArraysCore/uOYfN/src/GPUArraysCore.jl:103
 [3] setindex!
   @ ~/.julia/packages/GPUArrays/5XhED/src/host/indexing.jl:17 [inlined]
 [4] generic_randn(arraytype::Type{CuArray{T, 1} where T}, dim::Int64)
   @ NDTensors ~/.julia/packages/NDTensors/olKso/src/abstractarray/fill.jl:8
 [5] main()
   @ Main ~/ITensors.jl/NDTensors/ext/examples/NDTensorCUDA.jl:21
 [6] top-level scope
   @ ~/ITensors.jl/NDTensors/ext/examples/NDTensorCUDA.jl:116
in expression starting at /home/william/ITensors.jl/NDTensors/ext/examples/NDTensorCUDA.jl:116

```

</p></details>

**Version information**

 - Output from `versioninfo()`:
```julia

julia> versioninfo()
Julia Version 1.9.2
Commit e4ee485e909 (2023-07-05 09:39 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 12 × Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, skylake)
  Threads: 1 on 12 virtual cores
```

<details><summary>Other relevant version info</summary><p>

```julia

(it_test2) pkg> status ITensors
Status `~/it_test2/Project.toml`
  [9136182c] ITensors v0.3.42

(it_test2) pkg> status NDTensors
Status `~/it_test2/Project.toml`
  [23ae76d9] NDTensors v0.2.10

(it_test2) pkg> status CUDA
Status `~/it_test2/Project.toml`
  [052768ef] CUDA v4.4.1

julia> CUDA.versioninfo()
CUDA runtime 12.1, artifact installation
CUDA driver 12.2
NVIDIA driver 535.104.5

CUDA libraries: 
- CUBLAS: 12.1.3
- CURAND: 10.3.2
- CUFFT: 11.0.2
- CUSOLVER: 11.4.5
- CUSPARSE: 12.1.0
- CUPTI: 18.0.0
- NVML: 12.0.0+535.104.5

Julia packages: 
- CUDA: 4.4.1
- CUDA_Driver_jll: 0.5.0+1
- CUDA_Runtime_jll: 0.6.0+0

Toolchain:
- Julia: 1.9.2
- LLVM: 14.0.6
- PTX ISA support: 3.2, 4.0, 4.1, 4.2, 4.3, 5.0, 6.0, 6.1, 6.3, 6.4, 6.5, 7.0, 7.1, 7.2, 7.3, 7.4, 7.5
- Device capability support: sm_37, sm_50, sm_52, sm_53, sm_60, sm_61, sm_62, sm_70, sm_72, sm_75, sm_80, sm_86

1 device:
  0: NVIDIA GeForce RTX 3090 (sm_86, 22.728 GiB / 24.000 GiB available)
```

</p></details>

I am very new to Julia (and ITensors.jl), sorry if there is something obvious I'm missing!

### PR DESCRIPTION
**Pull request by kmp5VT**
# Description
In this PR I attempt to address issues we are having with generic programming. This issue is that wrapped arrays can become too complicated for Julia to parse correctly for dispatch and as a result, incorrect functions are called which in turn slows down the code.  Here I am creating a simple `Expose` type which will determine the base unwrapped type and launch the appropriate kernels based on this type.

This will fix #1193 (we should confirm that before merging).

# Checklist:

- [x] Create Expose type and function to create type.
- [x] Replace NDTensors code where we implicitly unwrap code (through parent_leaftype) and instead dispatch on the `expose` struct
- [x] Ensure that all tests still pass in NDTensors and ITensors
- [x] Fix scalar indexing issues in GPU SVD code
- [x] address merge conflicts

### CODE REVIEW

File: NDTensors/src/Unwrap/src/iswrappedarray.jl [hunk 1]
```diff
@@ -0,0 +1,57 @@
...
+
+# For working with instances, not used by
+# `SimpleTraits.jl` traits dispatch.
+is_wrapped_array(array::AbstractArray) = is_wrapped_array(typeof(array))
+
+# By default, the `parentype` of an array type is itself
+parenttype(arraytype::Type{<:AbstractArray}) = arraytype
+
+# TODO: Use `SetParameters` here.
+parenttype(::Type{<:Base.ReshapedArray{<:Any,<:Any,P}}) where {P} = P
```
Comment (mtfishman) [inline NDTensors/src/Unwrap/src/iswrappedarray.jl:25]: Since you used `using Base: ReshapedArray` above you should be able to just use `ReshapedArray` here, instead of `Base.ReshapedArray`.

File: NDTensors/src/Unwrap/src/Unwrap.jl [hunk 2]
```diff
@@ -0,0 +1,16 @@
+module Unwrap
+using SimpleTraits
+using LinearAlgebra
+using Base: ReshapedArray
+using Strided: StridedView
```
Comment (mtfishman) [inline NDTensors/src/Unwrap/src/Unwrap.jl:5]: Can use the more minimal [StridedViews.jl](https://github.com/Jutho/StridedViews.jl) which just defines `StridedView` that is used by `Strided.jl`.

Comment (kmp5VT) [reply NDTensors/src/Unwrap/src/Unwrap.jl]: I think I fixed this using `Strided.StridedViews` is that what you mean?

File: NDTensors/src/Unwrap/src/functions/permutedims.jl [hunk 3]
```diff
@@ -0,0 +1,3 @@
+function permutedims(E::Exposed{<:AbstractArray}, perm)
```
Comment (mtfishman) [inline NDTensors/src/Unwrap/src/functions/permutedims.jl:1]: For simplicity we could just use `::Exposed` instead of `::Exposed{<:AbstractArray}`.

File: NDTensors/ext/NDTensorsMetalExt/mul.jl [hunk 4]
```diff
@@ -1,15 +1,11 @@
...
 # TODO: Raise an issue with `Metal.jl`.
-function NDTensors.mul!!(
-  ::Type{<:MtlArray},
-  CM::Transpose,
-  ::Type{<:MtlArray},
-  AM::AbstractMatrix,
-  ::Type{<:MtlArray},
-  BM::AbstractMatrix,
+function LinearAlgebra.mul!(
+  CM::Unwrap.Exposed{<:MtlArray},
```
Comment (mtfishman) [inline NDTensors/ext/NDTensorsMetalExt/mul.jl:4]: I think this should be:
```julia
CM::Unwrap.Exposed{<:MtlArray,<:Transpose},
```
since there was only an issue in that case.

File: NDTensors/ext/NDTensorsMetalExt/permutedims.jl [hunk 5]
```diff
@@ -1,3 +1,10 @@
+function Base.permutedims!(
+  Edest::Unwrap.Exposed{<:MtlArray}, Esrc::Unwraped.Exposed{<:MtlArray}, perm
+)
+  Eperm = expose(permutedims(Esrc), perm)
```
Comment (mtfishman) [inline NDTensors/ext/NDTensorsMetalExt/permutedims.jl:4]: Looks like `perm` is not in the right location.

File: NDTensors/ext/NDTensorsMetalExt/permutedims.jl [hunk 6]
```diff
@@ -1,3 +1,10 @@
+function Base.permutedims!(
+  Edest::Unwrap.Exposed{<:MtlArray}, Esrc::Unwraped.Exposed{<:MtlArray}, perm
```
Comment (mtfishman) [inline NDTensors/ext/NDTensorsMetalExt/permutedims.jl:2]: Probably needs a more specific signature here since this shouldn't be used for all `MtlArray` operations, i.e. specialize on what wrapper type was giving trouble (I think `ReshapedArray`)?

File: NDTensors/src/Unwrap/src/Unwrap.jl [hunk 7]
```diff
@@ -0,0 +1,20 @@
...
+include("iswrappedarray.jl")
+include("expose.jl")
+
+include("import.jl")
+## TODO Create functions which take the `Expose` type and launch functions
+## using that type
+## Exposed based functions
+include("functions/permutedims.jl")
+
+export IsWrappedArray, is_wrapped_array, parenttype, unwrap_type, expose, Expose
```
Comment (mtfishman) [inline NDTensors/src/Unwrap/src/Unwrap.jl:16]: Should be `Exposed`, not `Expose`.

File: NDTensors/ext/NDTensorsMetalExt/permutedims.jl (hunk 6 above)
Comment (kmp5VT) [reply NDTensors/ext/NDTensorsMetalExt/permutedims.jl:2]: Makes sense! I knew there would be some issues with the metal implementation I just wasn't able to check on my workstation. I'm on my mac today and will verify this code. Thanks!

Comment (kmp5VT) [reply NDTensors/ext/NDTensorsMetalExt/permutedims.jl]: Ahh yes I see in the next line down you have `Adest::Base.ReshapedArray{<:Any,<:Any,<:SubArray}`  so I'll make `Edest::Exposed{<:MtlArray, <:ReshapedArray}` and will run tests to see if that works

File: NDTensors/ext/NDTensorsMetalExt/mul.jl [hunk 8]
```diff
@@ -1,15 +1,11 @@
...
+function LinearAlgebra.mul!(
+  CM::Exposed{<:MtlArray,<:Transpose},
+  AM::Exposed{<:MtlArray},
+  BM::Exposed{<:MtlArray},
   α,
   β,
 )
-  mul!(transpose(CM), transpose(BM), transpose(AM), α, β)
-  return CM
+  return mul!(transpose(CM.object), transpose(BM.object), transpose(AM.object), α, β)
```
Comment (mtfishman) [inline NDTensors/ext/NDTensorsMetalExt/mul.jl:10]: We should explicitly use `return CM` as before.

Again, for mutating/in-place functions (`f!(dest, ...)`) we should call it in a separate line and then return the modified value `dest`, since we can't assume the `f!` will in general return `dest`. For maybe-mutating functions (`f!!(dest, ...)`)  the convention is that they need to return `dest` so then what you wrote here would be ok.

File: NDTensors/ext/NDTensorsMetalExt/permutedims.jl [hunk 9]
```diff
@@ -1,3 +1,10 @@
+function Base.permutedims!(
+  Edest::Exposed{<:MtlArray,<:Base.ReshapedArray}, Esrc::Exposed{<:MtlArray}, perm
+)
+  Eperm = expose(permutedims(Esrc, perm))
```
Comment (mtfishman) [inline NDTensors/ext/NDTensorsMetalExt/permutedims.jl:4]: The way you have it written now, `expose` isn't doing anything since you just unwrap it in the next line.

Perhaps you want:
```julia
function Base.permutedims!(
  Edest::Exposed{<:MtlArray,<:Base.ReshapedArray}, Esrc::Exposed{<:MtlArray}, perm
)
  Eperm = expose(permutedims(Esrc, perm))
  copyto!(expose(parent(Edest.object)), Eperm)
  return Edest.object
end
```
Note that here I'm trying to ensure `Exposed` objects get passed to `copyto!`, in case there are issues that out own version of `copyto!` needs to fix for `MtlArray`.

I think there are a few things we need to establish in terms of conventions and semantics of `expose`:
1. We should define `unexpose(e::Exposed) = e.object` and prefer to use `unexpose`.
2. What should out-of-place functions that take `Exposed` objects as inputs return? I think they should output an unexposed object, i.e. `identity(e::Exposed) = unexpose(e)`, `permutedims(e::Exposed, perm) = permutedims(unexposed(e), perm)`, etc.
3. What should in-place functions that take `Exposed` objects return? I think they should return the modified unexposed object, i.e. `permutedims!(e::Exposed, perm) = (permutedims!(unexposed(e), perm); return unexposed(e))`.
4. Like I show above, we need to think carefully about when we `expose` or `unexpose` objects to not overuse it but try to anticipate potential issues that `expose` can fix.

File: NDTensors/ext/NDTensorsMetalExt/mul.jl (hunk 8 above)
Comment (mtfishman) [reply NDTensors/ext/NDTensorsMetalExt/mul.jl:10]: See my comment below about conventions of functions that accept `Exposed` objects, as well as other suggestions on semantics of `Exposed` objects.

Comment (mtfishman) [reply NDTensors/ext/NDTensorsMetalExt/mul.jl:10]: Not sure why `mul!!` would be removed, that function is still useful for performing maybe-mutating matrix multiplication. So I don't really understand your comment but maybe my comment below will clarify some things.

Comment (kmp5VT) [reply NDTensors/ext/NDTensorsMetalExt/mul.jl:10]: Your comment does make sense. I removed the `mul!!(CM, AM, BM, a, b)` function and replaced it with `Base.mul!(CM::Exposed, AM::Exposed, BM::Exposed, a, b)` and dispatch the correct `mul!` using the `Exposed` logic.  `mul!!` is not part of `LinearAlgebra`
```
julia> LinearAlgebra.mul!!
ERROR: UndefVarError: `mul!!` not defined
Stacktrace:
 [1] getproperty(x::Module, f::Symbol)
   @ Base ./Base.jl:31
 [2] top-level scope
   @ REPL[35]:1
   ```
but since it is  useful for the case you discuss I will add the function back into the `abstractarray` folder and define it as 
   ```
 function mul!!(CM::AbstractArray, AM::AbstractArray, BM::AbstractArray, a, b)
    mul!(expose(CM), expose(AM), expose(BM), a, b)
    return unexpose(CM)
```
Let me know if this is okay or if I should do more! Thanks for your comments!

Comment (mtfishman) [reply NDTensors/ext/NDTensorsMetalExt/mul.jl:10]: Sure, it's fine to have our own versions of functions that don't exist in `Base`, the goal is just to overload `Base` functions when we can.

I could imagine as an alternative that we define:
```julia
function mul!!(CM::AbstractArray, AM::AbstractArray, BM::AbstractArray, a, b)
 return mul!!(expose(CM), expose(AM), expose(BM), a, b)
end
```
and then have a version of `mul!!` defined on `Exposed` which likely then calls `mul!`. Not sure what is best here or if there is an application for that, I think it depends on how we end up using `mul!!`. As far as I know the main application we have for `mul!!` is handling the logic for allocating `UnallocatedZeros` so not sure how `Exposed` plays a role there.

Comment (mtfishman) [reply NDTensors/ext/NDTensorsMetalExt/mul.jl:10]: Maybe a strategy is to try to keep things similar to how we currently do things with `leaf_parenttype` dispatch.

File: NDTensors/ext/NDTensorsMetalExt/permutedims.jl (hunk 6 above)
Comment (mtfishman) [reply NDTensors/ext/NDTensorsMetalExt/permutedims.jl]: So probably it should be `Edest::Exposed{<:MtlArray,ReshapedArray{<:Any,<:Any,<:SubArray}}`, I don't think there was an issue with all `ReshapedArray`, just ones wrapping a `SubArray`.

File: NDTensors/ext/NDTensorsMetalExt/mul.jl (hunk 8 above)
Comment (kmp5VT) [reply NDTensors/ext/NDTensorsMetalExt/mul.jl:10]: Okay I understand! My thinking has been to make the `Exposed` system akin to the `leaf_parenttype` system and I'm just trying to be forward thinking about the extent of the system. In my work so far I am making it as light weight as possible. Thanks again for the direction.

Right now, I am not sure that we need the `mul!!(Exposed)` version right now. With the system I currently have implemented (I will push the changes in a minute) we should be able to define something like 
```
function mul!!(CM::UnallocatedZero, AM::AbstractArray, BM::AbstractArray, a, b)
  CM = allocate(CM)
  CM = mul!(expose(CM), expose(AM), expose(BM), a, b)
  return CM
```
which can cover the `UnallocatedZeros` logic in this case.

File: NDTensors/src/abstractarray/permutedims.jl [hunk 10]
```diff
@@ -1,50 +1,12 @@
...
 
 function permutedims!!(B::AbstractArray, A::AbstractArray, perm)
-  return permutedims!!(leaf_parenttype(B), B, leaf_parenttype(A), A, perm)
-end
-
-function permutedims!!(
-  Bleaftype::Type{<:AbstractArray}, B, Aleaftype::Type{<:AbstractArray}, A, perm
-)
-  permutedims!(leaf_parenttype(B), B, leaf_parenttype(A), A, perm)
+  Base.permutedims!(expose(B), expose(A), perm)
```
Comment (mtfishman) [inline NDTensors/src/abstractarray/permutedims.jl:5]: Reminder to drop `Base.`.

File: NDTensors/src/abstractarray/tensoralgebra/contract.jl [hunk 11]
```diff
@@ -97,12 +97,14 @@ function _contract_scalar_perm!(
       # Rᵃ .= β .* Rᵃ
       LinearAlgebra.scal!(length(Rᵃ), β, Rᵃ, 1)
     else
-      Rᵃ .= α .* permutedims(Tᵃ, perm) .+ β .* Rᵃ
+      Rᵃ .= α .* Base.permutedims(expose(Tᵃ), perm) .+ β .* Rᵃ
```
Comment (mtfishman) [inline NDTensors/src/abstractarray/tensoralgebra/contract.jl:100]: Reminder to drop `Base.`.

File: test/base/test_itensor_scalar_contract.jl [hunk 12]
```diff
@@ -65,14 +65,14 @@ end
 
     R .= A .* B
     @test !any(isnan, R)
-    @test array(R) ≈ NDTensors.permutedims(array(A), (2, 1, 3)) * array(B)[]
+    @test array(R) ≈ Base.permutedims(array(A), (2, 1, 3)) * array(B)[]
```
Comment (mtfishman) [inline test/base/test_itensor_scalar_contract.jl:68]: Reminder to drop `Base.`.

File: NDTensors/src/Unwrap/src/functions/permutedims.jl [hunk 13]
```diff
@@ -0,0 +1,14 @@
+function permutedims(E::Exposed, perm)
+  Aperm = permutedims(unexpose(E), perm)
+  return Aperm
```
Comment (mtfishman) [inline NDTensors/src/Unwrap/src/functions/permutedims.jl:3]:
```suggestion
  return permutedims(unexpose(E), perm)
```

File: NDTensors/ext/NDTensorsMetalExt/imports.jl [hunk 14]
```diff
@@ -1,5 +1,6 @@
 import NDTensors: mtl, set_ndims, set_eltype, set_eltype_if_unspecified
 import NDTensors.SetParameters: nparameters, get_parameter, set_parameter, default_parameter
+import NDTensors.Unwrap: Exposed
```
Comment (mtfishman) [inline NDTensors/ext/NDTensorsMetalExt/imports.jl:3]: You should use `using` here instead of `import`, `import` should only be used if you are overloading a function, as opposed to just making it available in the namespace.

File: NDTensors/ext/NDTensorsMetalExt/linearalgebra.jl [hunk 15]
```diff
@@ -1,15 +1,15 @@
-function NDTensors.qr(leaf_parenttype::Type{<:MtlArray}, A::AbstractMatrix)
-  Q, R = NDTensors.qr(NDTensors.cpu(A))
+function qr(A::Exposed{<:MtlArray})
+  Q, R = qr(expose(NDTensors.cpu(unexpose(A))))
```
Comment (mtfishman) [inline NDTensors/ext/NDTensorsMetalExt/linearalgebra.jl:2]: We could define `NDTensors.cpu(e::Exposed) = cpu(unexpose(e))` so we don't have to do this unwrapping here.

File: NDTensors/ext/NDTensorsMetalExt/mul.jl [hunk 16]
```diff
@@ -1,15 +1,12 @@
...
+function LinearAlgebra.mul!(
+  CM::Exposed{<:MtlArray,<:Transpose},
+  AM::Exposed{<:MtlArray},
+  BM::Exposed{<:MtlArray},
   α,
   β,
 )
-  mul!(transpose(CM), transpose(BM), transpose(AM), α, β)
-  return CM
+  mul!(transpose(unexpose(CM)), transpose(unexpose(BM)), transpose(unexpose(AM)), α, β)
```
Comment (mtfishman) [inline NDTensors/ext/NDTensorsMetalExt/mul.jl:10]: Could define `transpose(::Exposed)` to make this code simpler.

File: NDTensors/src/Unwrap/src/expose.jl [hunk 17]
```diff
@@ -0,0 +1,9 @@
+struct Exposed{Unwraped,Object}
+  object::Object
+end
+
+expose(object) = Exposed{unwrap_type(object),typeof(object)}(object)
+
+unexpose(E::Exposed) = E.object
+
+Base.parent(E::Exposed) = parent(unexpose(E))
```
Comment (mtfishman) [inline NDTensors/src/Unwrap/src/expose.jl:9]: I think this should be moved into a file in `Unwrap/src/functions/`.

File: NDTensors/src/Unwrap/src/functions/linearalgebra.jl [hunk 18]
```diff
@@ -0,0 +1,11 @@
+function qr(E::Exposed)
+  return qr(unexpose(E))
+end
+
+function eigen(E::Exposed)
+  return eigen(expose(E))
```
Comment (mtfishman) [inline NDTensors/src/Unwrap/src/functions/linearalgebra.jl:6]:
```suggestion
  return eigen(unexpose(E))
```

File: NDTensors/src/Unwrap/src/functions/linearalgebra.jl [hunk 19]
```diff
@@ -0,0 +1,11 @@
...
+end
+
+function svd(E::Exposed)
+  return svd(expose(E))
```
Comment (mtfishman) [inline NDTensors/src/Unwrap/src/functions/linearalgebra.jl:10]:
```suggestion
  return svd(unexpose(E))
```

File: NDTensors/src/Unwrap/src/functions/mul.jl [hunk 20]
```diff
@@ -0,0 +1,4 @@
+function LinearAlgebra.mul!(CM::Exposed, AM::Exposed, BM::Exposed, α, β)
```
Comment (mtfishman) [inline NDTensors/src/Unwrap/src/functions/mul.jl:1]:
```suggestion
function mul!(CM::Exposed, AM::Exposed, BM::Exposed, α, β)
```
since it looks like `mul!` is already imported.

File: NDTensors/src/arraytensor/array.jl [hunk 21]
```diff
@@ -61,8 +61,6 @@ end
 function permutedims!(
   output_array::MatrixOrArrayStorage, array::MatrixOrArrayStorage, perm, f::Function
 )
-  output_array = permutedims!!(
-    leaf_parenttype(output_array), output_array, leaf_parenttype(array), array, perm, f
-  )
+  output_array = permutedims!!(output_array, array, perm, f)
```
Comment (mtfishman) [inline NDTensors/src/arraytensor/array.jl:64]: Should this use `expose`?

File: NDTensors/src/blocksparse/blocksparse.jl [hunk 22]
```diff
@@ -104,7 +104,7 @@ end
 function copyto!(D1::BlockSparse, D2::BlockSparse)
   blockoffsets(D1) ≠ blockoffsets(D1) &&
     error("Cannot copy between BlockSparse storages with different offsets")
-  copyto!(data(D1), data(D2))
+  Base.copyto!(expose(data(D1)), expose(data(D2)))
```
Comment (mtfishman) [inline NDTensors/src/blocksparse/blocksparse.jl:107]: Is there a need for writing it as `Base.copyto!` instead of `copyto!`? I assume we are removing `NDTensors.copyto!`?

File: NDTensors/test/device_list.jl [hunk 23]
```diff
@@ -23,9 +23,9 @@ function devices_list(test_args)
   end
 
   if "metal" in test_args || "all" in test_args
-    push!(devs, NDTensors.mtl)
+    push!(devs, mtl)
     Metal.allowscalar()
-    include(joinpath(pkgdir(NDTensors), "ext", "examples", "NDTensorMetal.jl"))
+    #include(joinpath(pkgdir(NDTensors), "ext", "examples", "NDTensorMetal.jl"))
```
Comment (mtfishman) [inline NDTensors/test/device_list.jl:28]: Why is this dropped?

File: NDTensors/src/blocksparse/blocksparse.jl (hunk 22 above)
Comment (kmp5VT) [reply NDTensors/src/blocksparse/blocksparse.jl:107]: Thanks for pointing this out. Its the same as before, I implemented the `Base.copyto!` while still having the `NDTensors.copyto!` then removed the NDTensors version to see if/where things failed to replace them with base. But I forgot to go back and remove the `Base.` Ill go through and get rid of them. Same as the `LinearAlgebra.` in the `mul!` call above

File: NDTensors/src/Unwrap/src/functions/linearalgebra.jl (hunk 19 above)
Comment (kmp5VT) [reply NDTensors/src/Unwrap/src/functions/linearalgebra.jl:10]: Oh I am still working on decompositions (SVD, eigen QR, etc) so this was an accident that it was added here. Thanks though!

File: NDTensors/test/device_list.jl (hunk 23 above)
Comment (kmp5VT) [reply NDTensors/test/device_list.jl:28]: Sorry I commented it out while running tests on my machine, I'll add it back

File: NDTensors/src/arraytensor/array.jl (hunk 21 above)
Comment (kmp5VT) [reply NDTensors/src/arraytensor/array.jl:64]: No so `permutedims!!` as I have written will call `permutedims!(expose(output), expose(array), perm, f)` in case the type of `output` or `array` needs to be modified.

File: NDTensors/src/Unwrap/src/expose.jl (hunk 17 above)
Comment (kmp5VT) [reply NDTensors/src/Unwrap/src/expose.jl:9]: Okay! Makes sense I can define some of the other small functions like this in the same file

File: NDTensors/src/arraytensor/array.jl (hunk 21 above)
Comment (mtfishman) [reply NDTensors/src/arraytensor/array.jl:64]: Thanks, I think I got confused and was looking at an old version of the code, makes sense.

File: NDTensors/ext/NDTensorsMetalExt/linearalgebra.jl [hunk 24]
```diff
@@ -1,16 +1,30 @@
-function NDTensors.qr(leaf_parenttype::Type{<:MtlArray}, A::AbstractMatrix)
-  Q, R = NDTensors.qr(NDTensors.cpu(A))
-  return adapt(leaf_parenttype, Matrix(Q)), adapt(leaf_parenttype, R)
+function LinearAlgebra.qr(A::Exposed{<:MtlMatrix})
+  Q, R = LinearAlgebra.qr(expose(NDTensors.cpu(A)))
```
Comment (mtfishman) [inline NDTensors/ext/NDTensorsMetalExt/linearalgebra.jl:2]: Maybe we should use `using LinearAlgebra` so you can just use `qr` instead of `LinearAlgebra.qr`.

File: NDTensors/src/Unwrap/src/functions/util.jl [hunk 25]
```diff
@@ -0,0 +1,5 @@
+Base.parent(E::Exposed) = parent(unexpose(E))
```
Comment (mtfishman) [inline NDTensors/src/Unwrap/src/functions/util.jl:1]: Maybe we could call this file `abstractarray.jl` to indicate it is functionality focused on working with `AbstractArray` objects.

**Comment by mtfishman** [comment]
I left a few more comments about some stylistic changes but beyond that it looks good. Definitely a nice simplification over the previous `leaf_parenttype` dispatch we were using, and nice to make use of more `Base` functions directly. I guess the final step is using this new system to fix the last remaining scalar indexing issues?

**Comment by kmp5VT** [comment]
> I left a few more comments about some stylistic changes but beyond that it looks good. Definitely a nice simplification over the previous `leaf_parenttype` dispatch we were using, and nice to make use of more `Base` functions directly. I guess the final step is using this new system to fix the last remaining scalar indexing issues?

Thank you for the comments! Yes I am looking into the scalar indexing issues this morning!

File: NDTensors/ext/NDTensorsCUDAExt/indexing.jl [hunk 26]
```diff
@@ -1,8 +1,18 @@
...
-  CUDA.@allowscalar data(T)[] = x
-  return T
+function setindex!(E::Exposed{<:CuArray}, x::Number)
+  CUDA.@allowscalar unexpose(E)[] = x
+  return unexpose(E)
+end
+
+function Base.getindex(E::Exposed{<:CuArray,<:Adjoint}, I...)
+  Ep = parent(E)
+  return Base.getindex(Ep, I...)
```
Comment (mtfishman) [inline NDTensors/ext/NDTensorsCUDAExt/indexing.jl:12]:
```suggestion
  Ap = parent(E)
  return expose(Ap)[I...]
```

Comment (mtfishman) [reply NDTensors/ext/NDTensorsCUDAExt/indexing.jl:12]: I think the way you wrote it, `Ep` would not be `Exposed` since `parent` would unexpose it.

File: NDTensors/ext/NDTensorsCUDAExt/indexing.jl [hunk 27]
```diff
@@ -1,8 +1,18 @@
...
+end
+
+function Base.copy(E::Exposed{<:CuArray,<:Base.ReshapedArray})
+  Ep = parent(E)
+  return copy(Ep)
```
Comment (mtfishman) [inline NDTensors/ext/NDTensorsCUDAExt/indexing.jl:17]:
```suggestion
  Ap = parent(E)
  return copy(expose(Ap))
```

File: NDTensors/src/Unwrap/src/functions/abstractarray.jl [hunk 28]
```diff
@@ -0,0 +1,18 @@
+parent(E::Exposed) = parent(unexpose(E))
+
+transpose(E::Exposed) = transpose(unexpose(E))
+
+cpu(E::Exposed) = cpu(unexpose(E))
+
+getindex(E::Exposed) = getindex(unexpose(E))
```
Comment (mtfishman) [inline NDTensors/src/Unwrap/src/functions/abstractarray.jl:7]:
```suggestion
getindex(E::Exposed) = unexpose(E)[]
```

File: NDTensors/src/Unwrap/src/functions/abstractarray.jl [hunk 29]
```diff
@@ -0,0 +1,18 @@
...
+
+function setindex!(E::Exposed, x::Number)
+  setindex!(unexpose(E), x)
```
Comment (mtfishman) [inline NDTensors/src/Unwrap/src/functions/abstractarray.jl:10]:
```suggestion
  unexpose(E)[] = x
```

File: NDTensors/src/Unwrap/src/functions/abstractarray.jl [hunk 30]
```diff
@@ -0,0 +1,18 @@
...
+  return unexpose(E)
+end
+
+getindex(E::Exposed, I...) = getindex(unexpose(E), I...)
```
Comment (mtfishman) [inline NDTensors/src/Unwrap/src/functions/abstractarray.jl:14]:
```suggestion
getindex(E::Exposed, I...) = unexpose(E)[I...]
```

File: NDTensors/src/abstractarray/tensoralgebra/contract.jl [hunk 31]
```diff
@@ -162,13 +168,21 @@ function _contract!(
...
-  CM = mul!!(CM, AM, BM, El(α), El(β))
+  ## If C^T = A^T * B^T => C = B * A
+  ## TODO There is an issue in CUDA.jl
+  ## When all are transpose CUDA.mul! isn't being
+  ## Called correctly in `NDTensorsCUDAExt`
+  if AM isa Transpose && BM isa Transpose && CM isa Transpose
+    CM = mul!!(parent(CM), parent(BM), parent(AM), El(α), El(β))
+  else
+    CM = mul!!(CM, AM, BM, El(α), El(β))
+  end
```
Comment (mtfishman) [inline NDTensors/src/abstractarray/tensoralgebra/contract.jl:179]: Seems like this should use `expose`.

File: NDTensors/src/tensorstorage/tensorstorage.jl [hunk 32]
```diff
@@ -60,7 +60,9 @@ Base.real(S::TensorStorage) = setdata(S, real(data(S)))
 
 Base.imag(S::TensorStorage) = setdata(S, imag(data(S)))
 
-Base.copyto!(S1::TensorStorage, S2::TensorStorage) = (copyto!(data(S1), data(S2)); S1)
+function copyto!(S1::TensorStorage, S2::TensorStorage)
+  return (copyto!(expose(data(S1)), expose(data(S2))); S1)
```
Comment (mtfishman) [inline NDTensors/src/tensorstorage/tensorstorage.jl:64]:
```suggestion
  copyto!(expose(data(S1)), expose(data(S2)))
  return S1
```

File: NDTensors/src/abstractarray/tensoralgebra/contract.jl (hunk 31 above)
Comment (kmp5VT) [reply NDTensors/src/abstractarray/tensoralgebra/contract.jl:179]: This is the logic I made before with `permutedims!!` the `mul!!` calls `mul!(expose(CM), expose(AM), expose(BM), a, b)`

Comment (mtfishman) [reply NDTensors/src/abstractarray/tensoralgebra/contract.jl:179]: So maybe this should be handled with normal dispatch, i.e. define:
```julia
function mul!!(C::Transpose, A::Transpose, B::Transpose, α, β)
  CT = mul!!(transpose(C), transpose(B), transpose(A), α, β)
  return transpose(CT)
end
```
Note that we want to make sure it outputs the correctly transposed version. The point is more that this kind of logic should be handled outside of a high level function like `contract!`.

As a guiding principle, it is usually better to avoid code like `if A isa T ...` and instead use function dispatch.

Comment (kmp5VT) [reply NDTensors/src/abstractarray/tensoralgebra/contract.jl:179]: This makes a lot of sense, thanks! Also I am not sure that I need to return a transpose of CT because 
```
C(k,i)^T = A(j,i)^T B(k,j)^T => C(k,i) = B(k,j) A(j,i)
```

**Comment by mtfishman** [comment]
@kmp5VT I fixed the merge conflicts.

This looks good to go from my end, is this ready from your end? Any more scalar indexing issues you wanted to address?

**Comment by kmp5VT** [comment]
> Ah looks like some tests are failing, I introduced code into `main` that uses `leaf_parenttype` and `parenttype` which needs to get updated.

Yeah I found those areas and fixed them

**Comment by kmp5VT** [comment]
@mtfishman Okay this PR should be good now. Thanks!
